name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Isocalendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Licenses and permissions
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.licenses.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: repository
          repo: WAZUH
          plugin_licenses: yes
          plugin_licenses_setup: bash -c '[[ -f package.json ]] && npm ci || true'
